language: python
python:
  - "3.5"
  - "3.6"
cache: pip3
install:
  - "pip install sklearn scipy pyperclip"
script:
  - python -W"ignore" tests/conversion.py
os: "linux"
dist: "trusty"
notifications:
    on_success: never
    on_failure: never
